name: proyek_4_poki_polban_kita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  mongo_dart: ^0.10.8
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  flutter_markdown: ^0.7.7+1
  flutter_secure_storage: ^10.0.0
  uuid: ^4.5.3
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  bcrypt: ^1.2.0
  webview_flutter: ^4.10.0
  provider: ^6.1.5+1
  get: ^4.6.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env